"""
Generate cached Heisenberg Hamiltonian BSON files for the thesis-numerics
fixtures. Uses `find_typical_heisenberg` (W₂-spectral-median selection) so the
returned realisation is representative rather than an extremum — `find_ideal_*`
selects the outlier-max-min-gap sample and was found to distort downstream
plots at small `n`.

Produces a single 1D family:

  1D XXX with `[[Z], [Z, Z]]` disorder (strength 1.0), `batch_size=256`. Files
  `heis_xxx_zzdisordered_periodic_n{3..9}.bson`. The Z + ZZ disorder breaks the
  spin-flip ∏ X_i symmetry that an Z-only disorder would preserve and lifts the
  remaining accidental degeneracies, giving a non-degenerate spectrum at every n.

2D fixtures (`heis_xxz_2d_*.bson`) are intentionally NOT regenerated by this
script — the 2D `find_typical_2d_heisenberg` sweep is deferred. The existing
`heis_xxz_2d_*.bson` files on disk are find_ideal-generated and will be
migrated to find_typical when needed.

Usage:

    julia --project hamiltonians/generate_hamiltonians.jl                # laptop, n ≤ 9
    LAPTOP=false julia --project hamiltonians/generate_hamiltonians.jl   # cluster, allow n ≥ 10

The script prints the achieved `nu_min` and `typicality_distance` and warns
when `nu_min` is below the soft target 1e-4. The simulator does not require
`nu_min ≥ 1e-4`; smaller values just need finer simulator parameters at
consumption time.
"""

using QuantumFurnace
using Random
using BSON
using Printf

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------

const NU_MIN_TARGET = 1e-4
const SEED = 42                    # fixed seed for reproducibility
const LAPTOP = get(ENV, "LAPTOP", "true") == "true"
const LAPTOP_MAX_N = 9
const BATCH_SIZE = 256

# Approximate per-qubit BSON file size (bytes), measured empirically:
# n=3 → 6.6 KB, n=8 → 3.1 MB, n=9 → 13 MB → ~ 4× per qubit.
function _projected_bson_bytes(n::Int)
    return Int(round(6.6e3 * 4.0^(n - 3)))
end

const HAM_DIR = joinpath(dirname(@__DIR__), "hamiltonians")
isdir(HAM_DIR) || mkpath(HAM_DIR)

# -----------------------------------------------------------------------------
# Common helpers
# -----------------------------------------------------------------------------

function _save_and_report(path::String, hamiltonian::NamedTuple, label::String)
    # Use BSON.bson(path, Dict) instead of @save: the macro form has a known
    # truncation issue on BSON.jl 0.3.9 for large NamedTuples (≳ 32 MB on
    # virtio-fs in this Docker sandbox). The dict form serialises correctly.
    BSON.bson(path, Dict(:hamiltonian => hamiltonian))
    file_size_mb = filesize(path) / 1e6
    is_warning = hamiltonian.nu_min < NU_MIN_TARGET
    flag = is_warning ? "  ⚠️ below 1e-4 soft target" : ""
    typicality = hasproperty(hamiltonian, :typicality_distance) ?
                 (@sprintf("  typicality=%.3e", hamiltonian.typicality_distance)) : ""
    @printf("  saved %s  (%.2f MB)  nu_min=%.3e%s%s\n", basename(path),
        file_size_mb, hamiltonian.nu_min, typicality, flag)
end

function _abort_if_too_big(n::Int, family::String)
    if LAPTOP && n > LAPTOP_MAX_N
        projected_mb = _projected_bson_bytes(n) / 1e6
        @printf("\n[%s] n=%d would produce a ≈ %.0f MB BSON file; ", family, n, projected_mb)
        println("skipping on laptop. Set LAPTOP=false to override.")
        return true
    end
    return false
end

# -----------------------------------------------------------------------------
# 1D XXX with [[Z], [Z, Z]] disorder, W₂-spectral-median (typical) selection
# -----------------------------------------------------------------------------

function generate_1d_zz_typical(; n_range = 3:LAPTOP_MAX_N)
    println("\n=== 1D XXX + [[Z], [Z, Z]] disorder (find_typical, batch_size=$BATCH_SIZE) ===")
    coeffs = [1.0, 1.0, 1.0]
    dis_terms = [[Z], [Z, Z]]
    for n in n_range
        _abort_if_too_big(n, "1D-typical") && continue
        Random.seed!(SEED + 1000 + n)
        @printf("  n=%2d (dim=%4d): ", n, 2^n)
        raw = find_typical_heisenberg(n, coeffs;
            batch_size=BATCH_SIZE, periodic=true,
            disordering_terms=dis_terms, disorder_strength=1.0)
        path = joinpath(HAM_DIR, "heis_xxx_zzdisordered_periodic_n$(n).bson")
        _save_and_report(path, raw, "1D-typical")
    end
end

# -----------------------------------------------------------------------------
# Top level
# -----------------------------------------------------------------------------

println("Hamiltonian generation for thesis-numerics fixtures (qf-2kd)")
println("Output dir: ", HAM_DIR)
@printf("LAPTOP=%s, max n on laptop = %d. Set LAPTOP=false to override.\n",
    LAPTOP, LAPTOP_MAX_N)

generate_1d_zz_typical()

println("\nDone.")
